### PR TITLE
Add support for verilator linting

### PR DESCRIPTION
**Pull request by mmicko**
Toolchain is also ready at  https://github.com/mmicko/toolchain-verilator

### CODE REVIEW

**Comment by Jesus89** [comment]
This is awesome! Thanks for your work :smile:

The steps to include this new feature in the tool are:
- Build the new `toolchain-verilator` for all the architectures in Travis CI.
- Test the new `apio lint` command in all the OS.

In order to release and deploy the toolchain it would be nice to have the repo in the `FPGAwars` organization. You can transfer your repo if you like and I will give you permissions to it in the organization. Otherwise I can fork the repository.

Then, I will configure the token to enable deploy and check if it's OK for all the architectures.

NOTE: I have merged and deleted the `up5k` branch into `develop` (that's why the closed/reopened). Updated this PR's base branch to `develop`.

**Comment by mmicko** [comment]
Not a problem to transfer it at all.  Would like as well to keep it as part of FPGAwars organization.
Meanwhile will check what else could be changed to make this feature more useful.

**Comment by Jesus89** [comment]
Perfect. That would be great!

I have tested all the builds (except darwin) in local. Since we want to have all the packages statically built to avoid issues with old OS versions I have created [this PR](https://github.com/mmicko/toolchain-verilator/pull/1) with the updated configuration for static builds.

When the repo is in FPGAwars I will add the Travis CI configuration and create the first release :)

**Comment by Jesus89** [comment]
Invitation sent!

**Comment by Jesus89** [comment]
Toolchain-verilator v1.0.0 released: https://github.com/FPGAwars/toolchain-verilator/releases :tada:

**Comment by Jesus89** [comment]
I have finished the `apio lint` implementation and docs.

@mmicko if you are OK with it we can merge and release 0.4.0b2.

**Comment by mmicko** [comment]
I am fine with this. Would add some flags to do fine grade linting, but
that can wait.

**Comment by Jesus89** [comment]
OK, we have time for that. Let me know when the PR is ready to merge.

**Comment by mmicko** [comment]
Thing this should cover most of requirements, 3 more parameters. "top" to select top module (if needed), disable verilator style warnings, or disable specific warning (comma separated list)

**Comment by Jesus89** [comment]
Thanks. Docs updated. Ready to merge.

**Comment by mmicko** [comment]
Great. Thanks a lot for that.

**Pull request merged**
