### PR TITLE
Improvements for ECP5 and ICE40 flow

### PR DESCRIPTION
**Pull request by mmicko**
Many improvements done so far for ECP5 flow, also include usage of latest toolchains.
Support so far done mostly for ULX3S board from Radiona.
ICE40 flow now use nextpnr since arachne is anyway not supported and performance is now much better.

P.S. Still compiling all toolchain variations, will finish tonight all builds

### CODE REVIEW

**Comment by kost** [comment]
What is the status of this pull request? I'm already using it and it is working quite good.  I'm working on top of this to enable network flash of ecp5 by using ESP32 micropython:
https://github.com/kost/webrepl-python
https://github.com/kost/microftp-python

**Comment by Obijuan** [comment]
Merged! :-)
Thanks a lot Micko!!!  Such a great work!!!!!!!!!

**Comment by Obijuan** [comment]
Hi @mmicko !  I have merged the develop branch with the latest changes on master, into the develop branch. It would be great if you could test it again, and make sure nothing is broken. I cannot test with the ulx boards (i do not have still one)

I've tested with some ice40 boards and it seems to be ok

**Comment by mmicko** [comment]
@Obijuan Thanks for notification, tried with latest apio changes and it looks and works just fine.
If you need some test cases, to check builds there are some we used on workshop last year at :
https://github.com/ulx3s/fpga-odysseus/tree/master/tutorials

**Pull request merged**
